name: PR check
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['8']
        install-option: ['--minimum']
    name: Node v${{ matrix.node-version }} ${{ matrix.install-option }} 
    steps:
      - uses: actions/checkout@v1
      - name: Setting up Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version:  ${{ matrix.node-version }}
      - name: build
        run: |
          npm install ${{ matrix.install-option }}
          npm run lint
          npm run build
          npm run test